# pull official base image
FROM node:16
# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV REACT_APP_TMDB_API_KEY "71b210774480b37cc3325099149360ef"
ENV REACT_APP_API_ENDPOINT "http://localhost:4000"
ENV REACT_APP_CLOUDINARY_PRESET "moviecrit"
ENV REACT_APP_CLOUDINARY_CLOUD_NAME "chipi"

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . ./

# start app
CMD ["npm", "start"]